/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'cut' : IDL.Null,
  'focus' : IDL.Null,
  'mass' : IDL.Null,
  'recovery' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const ShippingInfo = IDL.Record({
  'zip' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'totalCents' : IDL.Nat,
  'shipping' : ShippingInfo,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'isLoyaltyMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([ShippingInfo], [IDL.Text], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'signupLoyalty' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'cut' : IDL.Null,
    'focus' : IDL.Null,
    'mass' : IDL.Null,
    'recovery' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const ShippingInfo = IDL.Record({
    'zip' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'totalCents' : IDL.Nat,
    'shipping' : ShippingInfo,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'isLoyaltyMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([ShippingInfo], [IDL.Text], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'signupLoyalty' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };