/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type Category = { 'cut' : null } |
  { 'focus' : null } |
  { 'mass' : null } |
  { 'recovery' : null };
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'totalCents' : bigint,
  'shipping' : ShippingInfo,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : string,
  'tagline' : string,
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : bigint,
}
export interface ShippingInfo {
  'zip' : string,
  'country' : string,
  'city' : string,
  'fullName' : string,
  'email' : string,
  'state' : string,
  'address' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'isLoyaltyMember' : ActorMethod<[string], boolean>,
  'placeOrder' : ActorMethod<[ShippingInfo], string>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'signupLoyalty' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];